Repository UBC-MDS/DSCI-532_2024_21_Job-Postings, pull requests merged in 2024-04, with the labels that each got.

#33 Add plot: Number of Job Postings by Region
  src/app.py
Labels: enhancement

#34 Fix readme and add the job posting map of US to the dashboard
  README.md
  src/app.py
Labels: enhancement

#36 Add the reflection for milestone 2
  reports/m2_reflection.md
Labels: documentation

#41 Fix color issue with dynamic update
  src/app.py
Labels: bug

#39 Update requirements.txt for rendering work
  requirements.txt
Labels: bug

#48 Fix mistake and add more features to the map
  src/app.py
Labels: enhancement

#50 Plot 4: add interactive map
  src/app.py
Labels: enhancement

#52 Update the layout using grid format
  src/app.py
Labels: enhancement

#54 add gif demo
  README.md
  img/bash_demo.gif
Labels: documentation

#53 Fix some parts of the dashboard
  src/app.py
Labels: enhancement

#58 Break code into multiple files
  src/__init__.py
  src/app.py
  src/callbacks.py
  src/components.py
  src/data.py
Labels: enhancement

#66 Fix source codes based on the feedbacks from Joel
  src/callbacks.py
  src/components.py
Labels: enhancement

#70 Tweak layout: Add side bar stretching the entire vertical viewport
  src/components.py
Labels: enhancement

#68 added minor changes
  src/callbacks.py
  src/components.py
Labels: enhancement

#71 Fix the dataset to only include yearly salaries
  src/callbacks.py
Labels: enhancement

#73 Add click feature to show the region
  src/callbacks.py
  src/components.py
Labels: enhancement

#84 Switching bar charts for a ranged chart
  src/callbacks.py
Labels: enhancement

#87 Seperate widgets & avoid crowded slider
  src/components.py
Labels: enhancement

#86 Add map click in dropdown and remove map title
  src/callbacks.py
Labels: enhancement

#93 Change bars to be less colorful
  src/callbacks.py
Labels: enhancement

#96 Indicate that map is clickable by changing cursor to a pointer & Enable selecting states using the lasso tool
  src/assets/custom_styles.css
  src/callbacks.py
  src/components.py
Labels: enhancement

#101 remove the bottom left bar chart
  src/app.py
  src/callbacks.py
  src/components.py
Labels: enhancement

#104 Challenging: add docstrings and tests
  environment.yaml
  reports/m4_reflection.md
  src/callbacks.py
  src/components.py
  src/data.py
  tests/__init__.py
  tests/test_components.py
  tests/test_data.py
Labels: enhancement
